apiVersion: v1
items:
- apiVersion: storage.k8s.io/v1
  kind: StorageClass
  metadata:
    name: faster
  provisioner: kubernetes.io/gce-pd
  parameters:
    type: pd-ssd
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: pgdata-claim
  spec:
    storageClassName: faster
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: walletstore-claim
  spec:
    storageClassName: faster
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: fabrichome-claim
  spec:
    storageClassName: ""
    volumeName: fabrichome-volume
    accessModes:
      - ReadOnlyMany
    resources:
      requests:
        storage: 100Mi
    selector:
      matchLabels:
        name: fabrichome-volume
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: fabrichome-volume
    labels:
      type: local
  spec:
    capacity:
      storage: 100Mi
    storageClassName: ""
    accessModes:
      - ReadOnlyMany
    claimRef:
      namespace: default
      name: fabrichome-claim
    gcePersistentDisk:
      pdName: balancetracker-disk
      fsType: ext4
      readOnly: true
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: couchdb-claim0
  spec:
    storageClassName: faster
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: couchdb-claim1
  spec:
    storageClassName: faster
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: orderer-disk-claim
  spec:
    storageClassName: faster
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: orderer-disk-claim1
  spec:
    storageClassName: faster
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: orderer-disk-claim2
  spec:
    storageClassName: faster
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: peer-disk-claim0
  spec:
    storageClassName: faster
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: peer-disk-claim1
  spec:
    storageClassName: faster
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
kind: List
metadata: {}

