apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      author: Interticket
      product: BalanceTracker
      version: uat
    creationTimestamp: null
    labels:
      balancetracker: setuppod
    name: setuppod
  spec:
    replicas: 1
    selector:
      matchLabels:
        balancetracker: setuppod
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          balancetracker: setuppod
      spec:
        restartPolicy: Always
        containers:
          - name: setupcontainer
            image: nginx
            command: ["/bin/sh", "-c", "--"]
            args:
              - echo "Mounting working directories";
                ls;
                cd /fabrichome;
                pwd;
                ls;            
                while true; do sleep 5; done;
            volumeMounts:
              - mountPath: /fabrichome
                name: fabrichome-claim-setup
        volumes:
          - name: fabrichome-claim-setup
            persistentVolumeClaim:
              claimName: fabrichome-claim
  status: {}
kind: List
metadata: {}

