apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      author: Interticket
      product: BalanceTracker
      version: dev
    creationTimestamp: null
    labels:
      balancetracker: explorerdb
    name: explorerdb
  spec:
    ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
    selector:
      balancetracker: explorerdb
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: pgdata-claim
  spec:
    storageClassName: standard
    volumeName: pgdata-volume
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 100Mi
    selector:
      matchLabels:
        name: pgdata-volume
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: pgdata-volume
    labels:
      type: local
  spec:
    capacity:
      storage: 100Mi
    storageClassName: standard
    accessModes:
      - ReadWriteMany
    hostPath:
      path: /home/hyperledgerdev/fabric-samples/balancetracker-test-kubernetes/pgdata
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      author: Interticket
      product: BalanceTracker
      version: dev
    creationTimestamp: null
    labels:
      balancetracker: explorerdb
    name: explorerdb
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          balancetracker: explorerdb
      spec:
        containers:
        - env:
          - name: DATABASE_DATABASE
            value: fabricexplorer
          - name: DATABASE_PASSWORD
            value: password
          - name: DATABASE_USERNAME
            value: hppoc
          image: hyperledger/explorer-db:latest
          name: explorerdb
          ports:
          - containerPort: 5432
          resources: {}
          volumeMounts:
          - mountPath: /docker-entrypoint-initdb.d/createdb.sh
            name: explorerdb-claim0
          - mountPath: /var/lib/postgresql/data
            name: pgdata-volume-claim
        hostname: explorerdb
        restartPolicy: Always
        volumes:
        - name: explorerdb-claim0
          hostPath:
            path: /hosthome/hyperledgerdev/fabric-samples/balancetracker-test-kubernetes/app/persistence/fabric/postgreSQL/db/
        - name: pgdata-volume-claim
          persistentVolumeClaim:
            claimName: pgdata-claim
  status: {}
kind: List
metadata: {}

