apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: kompose convert -f docker-compose.yml -o kubernetes2.yaml
      kompose.version: 1.16.0 (0c01309)
    creationTimestamp: null
    labels:
      io.kompose.service: ca-example-com
    name: ca-example-com
  spec:
    ports:
    - name: "7054"
      port: 7054
      targetPort: 7054
    selector:
      io.kompose.service: ca-example-com
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: kompose convert -f docker-compose.yml -o kubernetes2.yaml
      kompose.version: 1.16.0 (0c01309)
    creationTimestamp: null
    labels:
      io.kompose.service: couchdb
    name: couchdb
  spec:
    ports:
    - name: "5984"
      port: 5984
      targetPort: 5984
    selector:
      io.kompose.service: couchdb
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: kompose convert -f docker-compose.yml -o kubernetes2.yaml
      kompose.version: 1.16.0 (0c01309)
    creationTimestamp: null
    labels:
      io.kompose.service: orderer-example-com
    name: orderer-example-com
  spec:
    ports:
    - name: "7050"
      port: 7050
      targetPort: 7050
    selector:
      io.kompose.service: orderer-example-com
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: kompose convert -f docker-compose.yml -o kubernetes2.yaml
      kompose.version: 1.16.0 (0c01309)
    creationTimestamp: null
    labels:
      io.kompose.service: peer0-org1-example-com
    name: peer0-org1-example-com
  spec:
    ports:
    - name: "7051"
      port: 7051
      targetPort: 7051
    - name: "7053"
      port: 7053
      targetPort: 7053
    selector:
      io.kompose.service: peer0-org1-example-com
  status:
    loadBalancer: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -f docker-compose.yml -o kubernetes2.yaml
      kompose.version: 1.16.0 (0c01309)
    creationTimestamp: null
    labels:
      io.kompose.service: ca-example-com
    name: ca-example-com
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: ca-example-com
      spec:
        containers:
        - args:
          - sh
          - -c
          - fabric-ca-server start -b admin:adminpw
          env:
          - name: FABRIC_CA_HOME
            value: /etc/hyperledger/fabric-ca-server
          - name: FABRIC_CA_SERVER_CA_CERTFILE
            value: /etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem
          - name: FABRIC_CA_SERVER_CA_KEYFILE
            value: /etc/hyperledger/fabric-ca-server-config/4239aa0dcd76daeeb8ba0cda701851d14504d31aad1b2ddddbac6a57365e497c_sk
          - name: FABRIC_CA_SERVER_CA_NAME
            value: ca.example.com
          image: hyperledger/fabric-ca
          name: ca-example-com
          ports:
          - containerPort: 7054
          resources: {}
          volumeMounts:
          - mountPath: /etc/hyperledger/fabric-ca-server-config
            name: ca-example-com-claim0
        restartPolicy: Always
        volumes:
        - name: ca-example-com-claim0
          hostPath:
            path: /hosthome/hyperledgerdev/fabric-samples/balancetracker-test-network/crypto-config/peerOrganizations/org1.example.com/ca
  status: {}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: ca-example-com-claim0
    name: ca-example-com-claim0
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
  status: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -f docker-compose.yml -o kubernetes2.yaml
      kompose.version: 1.16.0 (0c01309)
    creationTimestamp: null
    labels:
      io.kompose.service: cli
    name: cli
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: cli
      spec:
        containers:
        - args:
          - /bin/bash
          env:
          - name: CORE_CHAINCODE_KEEPALIVE
            value: "10"
          - name: CORE_PEER_ADDRESS
            value: peer0.org1.example.com:7051
          - name: CORE_PEER_ID
            value: cli
          - name: CORE_PEER_LOCALMSPID
            value: Org1MSP
          - name: CORE_PEER_MSPCONFIGPATH
            value: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp
          - name: CORE_VM_ENDPOINT
            value: unix:///host/var/run/docker.sock
          - name: FABRIC_LOGGING_SPEC
            value: info
          - name: GOPATH
            value: /opt/gopath
          image: hyperledger/fabric-tools
          name: cli
          resources: {}
          tty: true
          volumeMounts:
          - mountPath: /host/var/run/
            name: cli-claim0
          - mountPath: /opt/gopath/src/github.com/
            name: cli-claim1
          - mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
            name: cli-claim2
          - mountPath: /opt/gopath/src/github.com/chaincode/
            name: cli-claim3
          - mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
            name: cli-claim4
          workingDir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        restartPolicy: Always
        volumes:
        - name: cli-claim0
          hostPath:
            path: /var/run/
        - name: cli-claim1
          hostPath:
            path: /hosthome/hyperledgerdev/fabric-samples/balancetracker-test-network/balancetracker-chaincode/
        - name: cli-claim2
          hostPath:
            path: /hosthome/hyperledgerdev/fabric-samples/balancetracker-test-network/crypto-config
        - name: cli-claim3
          hostPath:
            path: /hosthome/hyperledgerdev/fabric-samples/balancetracker-test-network/balancetracker-chaincode/
        - name: cli-claim4
          hostPath:
            path: /hosthome/hyperledgerdev/fabric-samples/balancetracker-test-network/scripts
  status: {}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: cli-claim0
    name: cli-claim0
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
  status: {}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: cli-claim1
    name: cli-claim1
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
  status: {}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: cli-claim2
    name: cli-claim2
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
  status: {}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: cli-claim3
    name: cli-claim3
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
  status: {}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: cli-claim4
    name: cli-claim4
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
  status: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -f docker-compose.yml -o kubernetes2.yaml
      kompose.version: 1.16.0 (0c01309)
    creationTimestamp: null
    labels:
      io.kompose.service: couchdb
    name: couchdb
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: couchdb
      spec:
        containers:
        - env:
          - name: COUCHDB_PASSWORD
          - name: COUCHDB_USER
          image: hyperledger/fabric-couchdb
          name: couchdb
          ports:
          - containerPort: 5984
          resources: {}
        restartPolicy: Always
  status: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -f docker-compose.yml -o kubernetes2.yaml
      kompose.version: 1.16.0 (0c01309)
    creationTimestamp: null
    labels:
      io.kompose.service: orderer-example-com
    name: orderer-example-com
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: orderer-example-com
      spec:
        containers:
        - args:
          - orderer
          env:
          - name: FABRIC_LOGGING_SPEC
            value: info
          - name: ORDERER_GENERAL_GENESISFILE
            value: /etc/hyperledger/configtx/genesis.block
          - name: ORDERER_GENERAL_GENESISMETHOD
            value: file
          - name: ORDERER_GENERAL_LISTENADDRESS
            value: 0.0.0.0
          - name: ORDERER_GENERAL_LOCALMSPDIR
            value: /etc/hyperledger/msp/orderer/msp
          - name: ORDERER_GENERAL_LOCALMSPID
            value: OrdererMSP
          image: hyperledger/fabric-orderer
          name: orderer-example-com
          ports:
          - containerPort: 7050
          resources: {}
          volumeMounts:
          - mountPath: /etc/hyperledger/configtx
            name: orderer-example-com-claim0
          - mountPath: /etc/hyperledger/msp/orderer
            name: orderer-example-com-claim1
          - mountPath: /etc/hyperledger/msp/peerOrg1
            name: orderer-example-com-claim2
          workingDir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
        restartPolicy: Always
        volumes:
        - name: orderer-example-com-claim0
          hostPath:
            path: /hosthome/hyperledgerdev/fabric-samples/balancetracker-test-network/config
        - name: orderer-example-com-claim1
          hostPath:
            path: /hosthome/hyperledgerdev/fabric-samples/balancetracker-test-network/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com
        - name: orderer-example-com-claim2
          hostPath:
            path: /hosthome/hyperledgerdev/fabric-samples/balancetracker-test-network/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/
  status: {}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: orderer-example-com-claim0
    name: orderer-example-com-claim0
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
  status: {}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: orderer-example-com-claim1
    name: orderer-example-com-claim1
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
  status: {}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: orderer-example-com-claim2
    name: orderer-example-com-claim2
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
  status: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -f docker-compose.yml -o kubernetes2.yaml
      kompose.version: 1.16.0 (0c01309)
    creationTimestamp: null
    labels:
      io.kompose.service: peer0-org1-example-com
    name: peer0-org1-example-com
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: peer0-org1-example-com
      spec:
        containers:
        - args:
          - peer
          - node
          - start
          env:
          - name: CORE_CHAINCODE_DEPLOYTIMEOUT
            value: 300s
          - name: CORE_CHAINCODE_EXECUTETIMEOUT
            value: 300s
          - name: CORE_CHAINCODE_LOGGING_LEVEL
            value: info
          - name: CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS
            value: couchdb:5984
          - name: CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
          - name: CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME
          - name: CORE_LEDGER_STATE_STATEDATABASE
            value: CouchDB
          - name: CORE_PEER_ADDRESS
            value: peer0.org1.example.com:7051
          - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
            value: peer0.org1.example.com:7051
          - name: CORE_PEER_ID
            value: peer0.org1.example.com
          - name: CORE_PEER_LOCALMSPID
            value: Org1MSP
          - name: CORE_PEER_MSPCONFIGPATH
            value: /etc/hyperledger/msp/peer/
          - name: CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE
            value: net_basic
          - name: CORE_VM_ENDPOINT
            value: unix:///host/var/run/docker.sock
          - name: FABRIC_LOGGING_SPEC
            value: info
          image: hyperledger/fabric-peer
          name: peer0-org1-example-com
          ports:
          - containerPort: 7051
          - containerPort: 7053
          resources: {}
          volumeMounts:
          - mountPath: /host/var/run/
            name: peer0-org1-example-com-claim0
          - mountPath: /etc/hyperledger/msp/peer
            name: peer0-org1-example-com-claim1
          - mountPath: /etc/hyperledger/msp/users
            name: peer0-org1-example-com-claim2
          - mountPath: /etc/hyperledger/configtx
            name: peer0-org1-example-com-claim3
          workingDir: /opt/gopath/src/github.com/hyperledger/fabric
        restartPolicy: Always
        volumes:
        - name: peer0-org1-example-com-claim0
          hostPath:
            path: /var/run/ 
        - name: peer0-org1-example-com-claim1
          hostPath:
            path: /hosthome/hyperledgerdev/fabric-samples/balancetracker-test-network/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp
        - name: peer0-org1-example-com-claim2
          hostPath:
            path: /hosthome/hyperledgerdev/fabric-samples/balancetracker-test-network/crypto-config/peerOrganizations/org1.example.com/users
        - name: peer0-org1-example-com-claim3
          hostPath:
            path: /hosthome/hyperledgerdev/fabric-samples/balancetracker-test-network/config/ 
  status: {}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: peer0-org1-example-com-claim0
    name: peer0-org1-example-com-claim0
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
  status: {}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: peer0-org1-example-com-claim1
    name: peer0-org1-example-com-claim1
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
  status: {}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: peer0-org1-example-com-claim2
    name: peer0-org1-example-com-claim2
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
  status: {}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: peer0-org1-example-com-claim3
    name: peer0-org1-example-com-claim3
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
  status: {}
kind: List
metadata: {}

