apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: pgdata-claim
  spec:
    storageClassName: standard
    volumeName: pgdata-volume
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 10Mi
    selector:
      matchLabels:
        name: pgdata-volume
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: pgdata-volume
    labels:
      type: local
  spec:
    capacity:
      storage: 10Mi
    storageClassName: standard
    accessModes:
      - ReadWriteMany
    hostPath:
      path: /home/hyperledgerdev/fabric-samples-interticket/balancetracker-test-kubernetes/pgdata
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: walletstore-claim
  spec:
    storageClassName: standard
    volumeName: walletstore-volume
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 10Mi
    selector:
      matchLabels:
        name: walletstore-volume
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: walletstore-volume
    labels:
      type: local
  spec:
    capacity:
      storage: 10Mi
    storageClassName: standard
    accessModes:
      - ReadWriteMany
    hostPath:
      path: /home/hyperledgerdev/fabric-samples-interticket/balancetracker-test-kubernetes/walletstore
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: fabrichome-claim
  spec:
    storageClassName: standard
    volumeName: fabrichome-volume
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 10Mi
    selector:
      matchLabels:
        name: fabrichome-volume
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: fabrichome-volume
    labels:
      type: local
  spec:
    capacity:
      storage: 10Mi
    storageClassName: standard
    accessModes:
      - ReadWriteMany
    hostPath:
      path: /home/hyperledgerdev/fabric-samples-interticket/balancetracker-test-kubernetes/
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: couchdb-claim
  spec:
    storageClassName: standard
    volumeName: couchdb-volume
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 10Mi
    selector:
      matchLabels:
        name: couchdb-volume
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: couchdb-volume
    labels:
      type: local
  spec:
    capacity:
      storage: 10Mi
    storageClassName: standard
    accessModes:
      - ReadWriteMany
    hostPath:
      path: /home/hyperledgerdev/fabric-samples-interticket/balancetracker-test-kubernetes/couchdb-volume/
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: orderer-claim
  spec:
    storageClassName: standard
    volumeName: orderer-volume
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 10Mi
    selector:
      matchLabels:
        name: orderer-volume
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: orderer-volume
    labels:
      type: local
  spec:
    capacity:
      storage: 10Mi
    storageClassName: standard
    accessModes:
      - ReadWriteMany
    hostPath:
      path: /home/hyperledgerdev/fabric-samples-interticket/balancetracker-test-kubernetes/orderer-volume/
kind: List
metadata: {}

