apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      author: Interticket
      product: BalanceTracker
      version: uat
    creationTimestamp: null
    labels:
      balancetracker: explorer
    name: explorer
  spec:
    type: NodePort 
    ports:
    - name: "8090"
      port: 8090
      targetPort: 8080
      nodePort: 31080
    selector:
      balancetracker: explorer
  status:
    loadBalancer: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      author: Interticket
      product: BalanceTracker
      version: uat
    creationTimestamp: null
    labels:
      balancetracker: explorer
    name: explorer
  spec:
    replicas: 1
    selector:
      matchLabels:
        balancetracker: explorer
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          balancetracker: explorer
      spec:
        containers:
        - args:
          - sh
          - -c
          - sleep 16&& node /opt/explorer/main.js && tail -f /dev/null
          env:
          - name: DATABASE_HOST
            value: explorerdb
          - name: DATABASE_PASSWD
            value: password
          - name: DATABASE_USERNAME
            value: Blockchain4ever
          - name: DISCOVERY_AS_LOCALHOST
            value: "false"
          image: hyperledger/explorer:latest
          name: explorer
          ports:
          - containerPort: 8080
          resources: {}
          volumeMounts:
          - mountPath: /opt/explorer/app/platform/fabric/
            name: explorer-claim0
            subPath: ./balancetracker-test-kubernetes/app/platform/fabric/
          - mountPath: /opt/explorer/app/platform/fabric/connection-profile
            name: explorer-claim0
            subPath: ./balancetracker-test-kubernetes/app/platform/fabric/connection-profile/
          - mountPath: /tmp/crypto
            name: explorer-claim0
            subPath: ./balancetracker-test-kubernetes/crypto-config/
          - mountPath: /opt/wallet
            name: walletstore-volume-claim
        hostname: explorer
        restartPolicy: Always
        volumes:
        - name: explorer-claim0
          persistentVolumeClaim:
            claimName: fabrichome-claim
#        - name: explorer-claim1
#          persistentVolumeClaim:
#            claimName: fabrichome-claim
#        - name: explorer-claim2
#          persistentVolumeClaim:
#            claimName: fabrichome-claim
        - name: walletstore-volume-claim
          persistentVolumeClaim:
            claimName: walletstore-claim
  status: {}
kind: List
metadata: {}

